### ISSUE TITLE
Complete the ROS observer generator

### ISSUE THREAD

**Issue by ipa-nhg** [ipa320/RosTooling#102]
Related to https://github.com/ipa320/ros-model/pull/100

- The observers generator allows only the selection of topics (publisher) to be monitored, it has to be extended for other interfaces: https://github.com/ipa320/ros-model/blob/945594e9370ab7470496cb246498b12323f14018/plugins/de.fraunhofer.ipa.ros.observer.generator/src/de/fraunhofer/ipa/ros/observer/GenerationHandler.java#L182-L203

- All the models generated have the same hard coded name "my_observer" https://github.com/ipa320/ros-model/blob/945594e9370ab7470496cb246498b12323f14018/plugins/de.fraunhofer.ipa.ros.observer.generator/src/de/fraunhofer/ipa/ros/observer/GenerationHandler.java#L112 this information should be given by the user 

- This generator should be extended to completely autogenerate a ROS package (the folder of the package, the package.xml and CMakeLists.txt files) -> the [rosgrap_monitor](https://github.com/ipa-hsd/rosgraph_monitor) has to be first updated to support this infrastructure

- Additionally we could play with parameters to generate observers ready to execute. Once the user select the topic to be subscribed a new dialog menu can show all fields of the message type, where the user can choose one of them. For that field the observer model set threshold values for the OK, WARNING and ERROR diagnostic status using parameters. Having this information the observer can be completely auto-generated. 

- Once the python code is consolidates we should add code generator Xtext tests -> https://github.com/ipa320/ros-model/blob/master/plugins/de.fraunhofer.ipa.ros.xtext.tests/src/de/fraunhofer/ipa/ros/tests/RosGeneratorTest.xtend

**Comment by ipa-nhg** [comment]
@ipa-hsd feel free to add further ToDos

**Comment by chcorbato** [comment]
Currently the observers are pre-defined to publish `Dignostic` messages. To start adding semantics I suggest the following improvements:

- [ ] Define a specific message type for Observers with semantics that capture most use cases for QA/QoS (QualityAttributes or Quality of Service) monitoring. E.f. `QAvalue.msg`
- [ ] For each observer, specify in the model the QA/QoS that the observer monitors, e.g. `safety`. An option for this could be to specify in the `observer.rossystem` a specific value for the corresponding field in the messages published. E.g. this would correspond to
```
QAvalue.msg
============
...
qa_type "safety"
value ...
```

**Comment by ipa-nhg** [comment]
The observers generator is not working in case the src-gen wasn't previously created by Xtend (and/or the auto build option of eclipse is disable)**. 
I could create statically the folder when the generator is called and in case doesn't exists. But I prefer to let Xtend to do that ( it contains a configuration to set the rights and find always the path), I should probably call first Xtend to prepare the creation of the python code. 

:exclamation: :exclamation: This issue has a high priority and must to be fixed for the next version.

** @chcorbato @marioney this was the issue I had yesterday during the TelCon, I couldn't sleep well thinking on that :laughing: :laughing:

**Comment by ipa-nhg** [comment]
partly solved https://github.com/ipa320/ros-model/commit/502e834ceac5fa33418e612749162ade3936af23
